list1=input("Enter the List elements: ").split(",")
print(list1)
print(type(list1[0]))
list1.append(55)
print(f"First List: {list1}")
print(f"First element of list: {list1[0]}")
print("Program Ended")
