r1=int(input("Enter The Number Of Row In A Matrix"))
c1=int(input("Enter The Number Of Column In A Matrix"))
r2=int(input("Enter The Number Of Row In B Matrix"))
c2= int(input("Enter The Number Of Column In B Matrix"))
print("Program Ended: ")
